name: leoaus
favicon: null
layout_spectrum: 0.15843
typography_spectrum: 0.36135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#73b2f5'
    - '#d8dde3'
    - '#251f2b'
    - '#6c6261'
    - '#ffc03d'
  brandStrength: 0.125
  lightness: 0.7338126637041569
  saturation: 0.08949117735028267
  rhythmicContrast: 0.22769060730934143
purpose: []
